roem_order = ['7', '8', '9', '10', 'boer', 'vrouw', 'heer', 'aas']
normal_order = ['7', '8', '9', 'boer', 'vrouw', 'heer', '10', 'aas']
trump_order = ['7', '8', '10', 'vrouw', 'heer', 'aas', '9', 'boer']
colors = ['harten', 'ruiten', 'schoppen', 'klaveren']
values = [('7', 0), ('8', 0), ('9', 0), ('10', 10), ('boer', 2), ('vrouw', 3), ('heer', 4), ('aas', 11)]
